"""auto_claude.run and auto_claude.summary — durable execution history.

Every write here is replay-safe by construction: inserts use
`ON CONFLICT (id) DO NOTHING` and updates are unconditional last-writer-wins
`SET`s, because `db/journal.py` may replay the same call twice if Postgres
drops the connection after committing but before acknowledging.

A `run` row cannot exist before its `issue_state` row does: `run.issue_id`
carries a real FK to `auto_claude.issue_state(issue_id)`, and `run.harness_id`
one to `auto_claude.harness(id)`. Same for `summary.issue_id` and
`summary.run_id`. Registering those parent rows first is the caller's
contract, not this module's — it has no visibility into whether they exist.
"""

from __future__ import annotations

import uuid

from db.pool import Database


def new_id() -> str:
    """A replay-safe primary key, generated by the caller, not the database."""
    return uuid.uuid4().hex


def start_run(
    db: Database, *, run_id: str, issue_id: str, harness_id: str,
    mode: str, model: str | None,
) -> None:
    """Open a `run` row. Replay-safe: a second call with the same id is a no-op."""
    db.execute(
        """
        INSERT INTO auto_claude.run (id, issue_id, harness_id, mode, model)
        VALUES (%s, %s, %s, %s, %s)
        ON CONFLICT (id) DO NOTHING
        """,
        (run_id, issue_id, harness_id, mode, model),
    )


def finish_run(
    db: Database, *, run_id: str, outcome: str, exit_code: int | None,
    duration_seconds: int | None, cost_usd: float | None, turns: int | None,
    crash_log_path: str | None,
) -> None:
    """Close a `run` row. Last-writer-wins: replaying is harmless."""
    db.execute(
        """
        UPDATE auto_claude.run
           SET ended_at = now(), outcome = %s, exit_code = %s,
               duration_seconds = %s, cost_usd = %s, turns = %s,
               crash_log_path = %s
         WHERE id = %s
        """,
        (outcome, exit_code, duration_seconds, cost_usd, turns, crash_log_path, run_id),
    )


def add_summary(
    db: Database, *, summary_id: str, issue_id: str, run_id: str | None,
    kind: str, body: str, comment_url: str | None,
) -> None:
    """Insert a `summary` row. Replay-safe: a second call with the same id is a no-op."""
    db.execute(
        """
        INSERT INTO auto_claude.summary (id, issue_id, run_id, kind, body, comment_url)
        VALUES (%s, %s, %s, %s, %s, %s)
        ON CONFLICT (id) DO NOTHING
        """,
        (summary_id, issue_id, run_id, kind, body, comment_url),
    )
